#!/usr/bin/env bash

if ! command -v curl >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
  if ! command -v notify-send >/dev/null 2>&1; then
    echo "Error: The 'curl', 'notify-send' and 'jq' tools are required but not installed for $0."
  else
    notify-send -u critical "Error" "The 'curl' and 'jq' tools are required but not installed for $0."
  fi
  exit 1
fi

response="$(curl -s https://ipinfo.io | jq -r '.loc' | tr ',' ':')"

if [ $? -ne 0 ] || [ -z "$response" ]; then
  echo "Error: Failed to fetch weather data." >&2
  exit 1
fi

echo "$response"
