return {
  require("plugins.ui.alpha"),
  require("plugins.ui.catppuccin"),
  require("plugins.ui.colorizer"),
  require("plugins.ui.delimiter"),
  require("plugins.ui.dropbar"),
  -- require("plugins.ui.incline"),
  require("plugins.ui.indent"),
  require("plugins.ui.lualine"),
  require("plugins.ui.md-preview"),
  require("plugins.ui.md-render"),
  require("plugins.ui.noice"),
  require("plugins.ui.snacks"),
  require("plugins.ui.smear"),
  require("plugins.ui.statuscol"),
  require("plugins.ui.todo"),
  require("plugins.ui.ufo"),
  require("plugins.ui.web-devicons"),
  require("plugins.ui.whichkey"),
  require("plugins.ui.wrapwidth"),
}