nix-flake-hook() {
  [[ -n "$IN_NIX_SHELL" ]] && return

  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    if [[ -f "$dir/flake.nix" ]]; then
      if [[ ! -f "$dir/.envrc" ]]; then
        cat >"$dir/.envrc" <<'EOF'
# autogenerated: load flake dev environment
eval "$(nix print-dev-env)"
EOF
        command direnv allow "$dir" >/dev/null 2>&1
      fi

      command direnv reload >/dev/null 2>&1
      return
    fi
    dir="${dir:h}"
  done
}

add-zsh-hook chpwd nix-flake-hook
nix-flake-hook
