return {
  "williamboman/mason-lspconfig.nvim",
  -- event = { "LspAttach" },
  opts = {
    ensure_installed = {
      "arduino_language_server",
      "bashls",
      "clangd",
      "cmake",
      "csharp_ls",
      "gopls",
      "gradle_ls",
      "html",
      "intelephense",
      "jdtls",
      "jsonls",
      "kotlin_language_server",
      "ltex",
      "lua_ls",
      "matlab_ls",
      "omnisharp",
      "pylsp",
      "pyright",
      "rust_analyzer",
      "sqlls",
      "ts_ls",
      "vimls",
      "zls",
      "taplo",
      "asm_lsp",
      "cssls",
      "somesass_ls",
      "tailwindcss",
      "cssmodules_ls",
      "svelte",
      "graphql",
      "emmet_ls",
      "prismals",
      "clojure_lsp",
      "nil_ls",
      "rnix",
      "hyprls",
    },
    automatic_installation = true,
  },
}
