source "~/.config/tmux/themes/catppuccin-frappe.conf"
source "~/.config/tmux/theme.conf"
source "~/.config/tmux/bindings.conf"
source "~/.config/tmux/options.conf"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin 'aserowy/tmux.nvim'
# set -g @plugin 'tmux-plugins/tmux-pain-control'
# set -g @plugin "tmux-plugins/tmux-sidebar"
set -g @plugin "tmux-plugins/tmux-sensible"
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin "tmux-plugins/tmux-sessionist"
set -g @plugin "tmux-plugins/tmux-yank"
# set -g @plugin "tmux-plugins/tmux-copycat"
# set -g @plugin "tmux-plugins/tmux-open"
set -g @plugin "tmux-plugins/tmux-prefix-highlight"
# set -g @plugin "catppuccin/tmux"
# set -g @plugin 'jimeh/tmux-themepack'

# set -g @plugin 'arl/tmux-gitbar'
# set -g @plugin 'ChanderG/tmux-notify'
# set -g @plugin 'jabirali/tmux-tilish'
# set -g @plugin 'casonadams/tmux-workspace'
# set -g @plugin 'tmux-plugins/tmux-urlview'
# set -g @plugin 'nhdaly/tmux-better-mouse-mode'

# set -g @resurrect-capture-pane-contents 'on'
#
# set -g @continuum-restore 'on'
# set -g @continuum-save-interval '1'
#
# set-hook -ga pane-exited 'run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh quiet"'
# set-hook -ga session-closed 'run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh quiet"'

run "~/.config/tmux/plugins/tpm/tpm"
