indent_type = "Spaces"
indent_width = 2
column_width = 120
quote_style = "AutoPreferDouble"
collapse_simple_statement = "Never"
space_after_function_names = "Never"
# call_parentheses = "NoSingleString"
syntax = "All"
[sort_requires]
enabled = true
