require('awful').spawn.with_shell('autostart')
require("beautiful").init(require("gears").filesystem.get_configuration_dir() .. Theme)
require('configs.notifications')
require('configs.keys')
require('configs.rules')
require('configs.ui')
