require("utils.mason_ensure").ensure({
	"typescript-language-server",
	"tailwindcss-language-server",
	"unocss-language-server",
	"eslint_d",
	"biome",
	"prettierd",
	"prettier",
	"js-debug-adapter",
	"firefox-debug-adapter",
})
