return {
  "xiyaowong/transparent.nvim",
  event = { "VimEnter" },
  -- lazy=false,
  config = function()
    require("transparent").setup({
      groups = {
        "Normal",
        "NormalNC",
        "Comment",
        "Constant",
        "Special",
        "Identifier",
        "Statement",
        "PreProc",
        "Type",
        "Underlined",
        "Todo",
        "String",
        "Function",
        "Conditional",
        "Repeat",
        "Operator",
        "Structure",
        "LineNr",
        "NonText",
        "SignColumn",
        "CursorLine",
        "CursorLineNr",
        "StatusLine",
        "StatusLineNC",
        "EndOfBuffer",
        "Folded",
        "SpecialKey",
        "VertSplit",
        "BqfPreviewFloat",
        "BqfPreviewBorder",
        "BqfPreviewTitle",
        "BqfPreviewThumb",
        "BqfPreviewSbar",
        "BqfPreviewCursor",
        "BqfPreviewCursorLine",
        "BqfPreviewRange",
        "BqfPreviewBufLabel",
        "BqfSign",
      },
      extra_groups = {},
      exclude_groups = {},
      on_clear = function() end,
    })
  end,
}
