-- vim.filetype.add({
--   pattern = {
--     [".*/hypr/.*%.conf"] = "hyprlang",
--     ["hypr*.conf"] = "hyprlang",
--     [".*%.hl"] = "hyprlang",
--   },
-- })

-- vim.api.nvim_create_autocmd({ "BufEnter", "BufWinEnter" }, {
--   pattern = { "*.hl", "hypr*.conf" },
--   callback = function()
--     -- vim.lsp.start({
--     --   name = "hyprlang",
--     --   cmd = { "hyprls" },
--     --   root_dir = vim.fn.getcwd(),
--     -- })
--   end,
-- })
