return {
  -- lsp
  "angularls",
  "arduino_language_server",
  "asm_lsp",
  "bashls",
  "biome",
  "clojure_lsp",
  "cmake",
  "clangd",
  "somesass_ls",
  "tailwindcss",
  "unocss",
  "docker_compose_language_service",
  "dockerls",
  "fsautocomplete",
  "gopls",
  "gradle_ls",
  "graphql",
  "hls",
  "html",
  "hyprls",
  "jdtls",
  "jsonls",
  "kotlin_language_server",
  "lua_ls",
  "marksman",
  "matlab_ls",
  "mesonlsp",
  "nil_ls",
  "intelephense",
  "prismals",
  "protols",
  "pylsp",
  "ruby_lsp",
  "rust_analyzer",
  "slint_lsp",
  "sqlls",
  "svelte",
  "taplo",
  "yamlls",
  "ts_ls",
  "vimls",
  "lemminx",
  "zls",

  -- formatters and linters
  "stylua",
  "editorconfig-checker",
  "golangci-lint",
  "gofumpt",
  -- "golines",
  "gomodifytags",
  "gotests",
  "impl",
  "json-to-struct",
  -- "luacheck",
  "misspell",
  "codespell",
  "cspell",
  "revive",
  -- "shfmt",
  -- "beautysh",
  "staticcheck",
  "vint",
  "eslint_d",
  "rubocop",
  "black",
  "blue",
  "clang-format",
  "isort",
  "prettier",
  "prettierd",
  "ktlint",
  "pylint",
  "mypy",
  "ruff",
  "clj-kondo",
  "google-java-format",
  "gersemi",
  "buf",
  "standardrb",
  "yamlfix",
  "asmfmt",
  "nixpkgs-fmt",
  "gdtoolkit",
  "biome",
  "cmakelang",
  "doctoc",
  "erb-formatter",
  "fantomas",
  "fourmolu",
  "htmlbeautifier",
  "markdown-toc",
  "markdownlint",
  "mdformat",
  "ormolu",
  "rubyfmt",
  "rufo",
  "yapf",
  "bacon",
  "checkmake",
  "cmakelint",
  -- "cpplint",
  "erb-lint",
  "hadolint",
  "hlint",
  "protolint",
  "pyflakes",
  "dcm",

  -- dap
  "delve",
  "codelldb",
  "cortex-debug",
  "cpptools",
  "python", -- debugpy",
  "js-debug-adapter",
  -- "chrome-debug-adapter",
  "firefox", -- "firefox-debug-adapter",
  -- "node-debug2-adapter",
  "dart-debug-adapter",
  -- "kotlin-debug-adapter",
  "netcoredbg",
}
