
add_newline = true

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$sudo\
$vcsh\
(↓ Source control - for right side ↓)\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
(↑ Source control - for right side ↑)\
$pijul_channel\
$docker_context\
$package\
(↓ Toolchain version modules ↓)\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
(↑ Toolchain version modules ↑)\
(↓ Package modules ↓)\
$aws\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
(↑ Package modules ↑)\
$memory_usage\
$cmd_duration\
$battery\
$status\
$os\
$container\
$character"""

# $gcloud\

[username]
format = "[$user]($style)"
show_always = false
style_root = "bold blue"
style_user = "bold cyan"

[hostname]
format = "[@](bold white)[$hostname]($style) in "
ssh_only = true
style = "bold dimmed green"
# trim_at = "-"

[sudo]
format = "[as $symbol ]($style)"
allow_windows = true
style = "bold red"
symbol = "root"
disabled = false

[directory]
format = "[$path ]($style)[$read_only]($read_only_style)"
style = "cyan"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "
read_only = "  "
read_only_style = "fg:blue bold"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[](bold blue)"  # ❱❯
vicmd_symbol = "[λ](bold magenta)"

[git_branch]
symbol = " "
truncation_symbol = " "

[git_commit]
commit_hash_length = 4
only_detached = true

[git_state]
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"

[git_status]
conflicted = "${count}"
ahead = "${count}⇡"
behind = "${count}⇣"
diverged = "(${ahead_count}⇡${behind_count}⇣)⇕"
# up_to_date = '✓'
untracked = "${count}?"
stashed = "${count}"
modified = "${count}!"
# staged = "${count}"
staged = '[++\($count\)](green)'
renamed = "${count}"
deleted = "${count}"
# typechanged = ""
