format = """$directory$character"""

add_newline = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "cyan"
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'
read_only = "  "
read_only_style = "fg:blue bold"

[character]
error_symbol = "[ﬀ](bold red)"
success_symbol = "[ﬀ](bold blue)"  # ❱❯ ﬀ

