title   Arch Linux (linux-hardened)
linux   /vmlinuz-linux-hardened
initrd  /initramfs-linux-hardened.img
options root=/dev/ArchinstallVg/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs quiet splash nowatchdog nmi_watchdog=0
