return {
  "williamboman/mason-lspconfig.nvim",
  dependencies = {
    "williamboman/mason.nvim",
  },
  opts = {
    automatic_enable = true,
    ensure_installed = {
      "angularls",
      "arduino_language_server",
      "asm_lsp",
      "bashls",
      "biome",
      "clojure_lsp",
      "cmake",
      "clangd",
      -- "omnisharp",
      -- csharp_ls
      -- omnisharpmono
      -- "css_ls",
      "somesass_ls",
      -- "css_variables",
      -- "cssmodules_ls",
      "tailwindcss",
      "unocss",
      -- "dartls",
      "docker_compose_language_service",
      "dockerls",
      -- "emmet_ls",
      -- "eslint",
      "fsautocomplete",
      -- "gleam",
      "gopls",
      -- "gdscript",
      -- "gdshader_lsp",
      "gradle_ls",
      -- "grammarly",
      "graphql",
      "hls",
      "html",
      "hyprls",
      "jdtls",
      "jsonls",
      "kotlin_language_server",
      "ltex",
      "lua_ls",
      -- "checkmake",
      "marksman",
      "matlab_ls",
      "mesonlsp",
      -- "rnix",
      "nil_ls",
      "intelephense",
      "prismals",
      -- "buf_ls",
      "protols",
      -- "pbls",
      "pylsp",
      -- "pyright",
      -- "ruff",
      -- "pylyzer",
      -- "django_template_lsp",
      -- "rubocop",
      "ruby_lsp",
      "rust_analyzer",
      "slint_lsp",
      "sqlls",
      -- "sqls",
      "svelte",
      -- "sourcekit",
      "taplo",
      "ts_ls",
      "vimls",
      "lemminx",
      "zls",
      -- "roslyn",
      -- "rzls",
      -- "copilot",
    },
  },
}
