source = $XDG_CONFIG_HOME/hypr/monitors.conf

source = $XDG_CONFIG_HOME/hypr/themes/frappe.hl

source = $XDG_CONFIG_HOME/hypr/configs/plugins.hl

source = $XDG_CONFIG_HOME/hypr/configs/bindings.hl
source = $XDG_CONFIG_HOME/hypr/configs/gestures.hl
source = $XDG_CONFIG_HOME/hypr/configs/layouts.hl
source = $XDG_CONFIG_HOME/hypr/configs/style.hl

exec-once = autostart
