return {
  require("plugins.tools.bqf"),
  require("plugins.tools.dadbod"),
  require("plugins.tools.dbee"),
  -- require("plugins.tools.harpoon"),
  require("plugins.tools.multicursor"),
  require("plugins.tools.neotree"),
  require("plugins.tools.ng"),
  require("plugins.tools.oil"),
  require("plugins.tools.oscyank"),
  require("plugins.tools.outline"),
  require("plugins.tools.persisted"),
  require("plugins.tools.spider"),
  require("plugins.tools.surround"),
  require("plugins.tools.telescope"),
  require("plugins.tools.tmux"),
  require("plugins.tools.undotree"),
}
