return {
  require("plugins.tools.autopair"),
  require("plugins.tools.autosession"),
  require("plugins.tools.autotag"),
  require("plugins.tools.bqf"),
  require("plugins.tools.comment"),
  require("plugins.tools.crates"),
  require("plugins.tools.dadbod"),
  require("plugins.tools.flash"),
  require("plugins.tools.harpoon"),
  require("plugins.tools.kulala"),
  require("plugins.tools.multicursor"),
  require("plugins.tools.ng"),
  require("plugins.tools.oil"),
  require("plugins.tools.outline"),
  require("plugins.tools.package-info"),
  require("plugins.tools.pubspec-assist"),
  require("plugins.tools.refactor"),
  ---@diagnostic disable-next-line: different-requires
  require("plugins.tools.schema-companion"),
  require("plugins.tools.spider-motion"),
  require("plugins.tools.surround"),
  require("plugins.tools.tmux"),
  require("plugins.tools.trouble"),
}