bg="#1e1e2e"
fg="#cdd6f4"
cyan="#89dceb"
black="#181825"
gray="#313244"
magenta="#cba6f7"
pink="#f5c2e7"
red="#f38ba8"
green="#a6e3a1"
yellow="#f9e2af"
blue="#89b4fa"
orange="#fab387"
black4="#585b70"

# vim: ft=tmux
