return {
  {
    "williamboman/mason.nvim",
    lazy = false,
    priority = 100,
    build = ":MasonUpdate",
    dependencies = {
      "nvim-telescope/telescope.nvim",
    },
    keys = {
      {
        "<leader>mm",
        "<cmd>Mason<CR>",
        { noremap = true, silent = true },
      },
    },
    opts = {
      registries = {
        "github:mason-org/mason-registry",
        "github:nvim-java/mason-registry",
        "github:crashdummyy/mason-registry",
      },
    },
  },

  {
    "williamboman/mason-lspconfig.nvim",
    lazy = false,
    dependencies = {
      "williamboman/mason.nvim",
      "neovim/nvim-lspconfig",
    },
    opts = {
      automatic_enable = true,
      ensure_installed = {
        "angularls",
        "arduino_language_server",
        "asm_lsp",
        "bashls",
        "biome",
        "clojure_lsp",
        "cmake",
        "clangd",
        "somesass_ls",
        "tailwindcss",
        "unocss",
        "docker_compose_language_service",
        "dockerls",
        "fsautocomplete",
        "gopls",
        "gradle_ls",
        "graphql",
        "hls",
        "html",
        "hyprls",
        "jdtls",
        "jsonls",
        "kotlin_language_server",
        "lua_ls",
        "marksman",
        "matlab_ls",
        "mesonlsp",
        "nil_ls",
        "intelephense",
        "prismals",
        "protols",
        "pylsp",
        "ruby_lsp",
        "rust_analyzer",
        "slint_lsp",
        "sqlls",
        "svelte",
        "taplo",
        "yamlls",
        "ts_ls",
        "vimls",
        "lemminx",
        "zls",
      },
      servers = {
        gradle_ls = {
          settings = {},
          init_options = {
            settings = {
              gradleWrapperEnabled = true,
            },
          },
        },
      },
    },
  },

  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    event = "VeryLazy",
    dependencies = {
      "williamboman/mason.nvim",
    },
    opts = {
      auto_update = true,
      run_on_start = true,
      debounce_hours = 24,
      ensure_installed = {
        "stylua",
        "editorconfig-checker",
        "golangci-lint",
        "gofumpt",
        "golines",
        "gomodifytags",
        "gotests",
        "impl",
        "json-to-struct",
        "luacheck",
        "misspell",
        "codespell",
        "cspell",
        "revive",
        "shfmt",
        "beautysh",
        "staticcheck",
        "vint",
        "eslint_d",
        "rubocop",
        "black",
        "blue",
        "clang-format",
        "isort",
        "prettier",
        "prettierd",
        "ktlint",
        "pylint",
        "mypy",
        "ruff",
        "clj-kondo",
        "google-java-format",
        "gersemi",
        "buf",
        "standardrb",
        "yamlfix",
        "asmfmt",
        "nixpkgs-fmt",
        "gdtoolkit",
        "biome",
        "cmakelang",
        "doctoc",
        "erb-formatter",
        "fantomas",
        "fourmolu",
        "htmlbeautifier",
        "markdown-toc",
        "markdownlint",
        "mdformat",
        "ormolu",
        "rubyfmt",
        "rufo",
        "yapf",
        "bacon",
        "checkmake",
        "cmakelint",
        "cpplint",
        "erb-lint",
        "hadolint",
        "hlint",
        "protolint",
        "pyflakes",
        "dcm",
      },
    },
  },

  {
    "jay-babu/mason-nvim-dap.nvim",
    event = "VeryLazy",
    dependencies = {
      "mfussenegger/nvim-dap",
      "williamboman/mason.nvim",
    },
    opts = {
      ensure_installed = {
        "delve",
        "codelldb",
        "cortex-debug",
        "cpptools",
        "python",
        "js-debug-adapter",
        "firefox",
        "dart-debug-adapter",
        "netcoredbg",
      },
      automatic_installation = true,
    },
  },
}
