return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  dependencies = {
    "williamboman/mason.nvim",
  },
  opts = {
    auto_update = true,
    run_on_start = true,
    ensure_installed = {
      "stylua",
      -- "shellcheck",
      "editorconfig-checker",
      "golangci-lint",
      "gofumpt",
      "golines",
      "gomodifytags",
      "gotests",
      "impl",
      "json-to-struct",
      "luacheck",
      "misspell",
      "codespell",
      "cspell",
      "revive",
      "shfmt",
      "beautysh",
      "staticcheck",
      "vint",
      "eslint_d",
      "rubocop",
      "black",
      "blue",
      "clang-format",
      "isort",
      "prettier",
      "prettierd",
      "ktlint",
      "pylint",
      "mypy",
      "ruff",
      "clj-kondo",
      "google-java-format",
      "gersemi",
      "buf",
      "standardrb",
      "yamlfix",
      "asmfmt",
      "nixpkgs-fmt",
      "gdtoolkit",
      "biome",
      "cmakelang",
      "doctoc",
      "erb-formatter",
      "fantomas",
      "fourmolu",
      "htmlbeautifier",
      "markdown-toc",
      "markdownlint",
      "mdformat",
      "ormolu",
      "rubyfmt",
      "rufo",
      "yapf",
      "bacon",
      "checkmake",
      "cmakelint",
      "cpplint",
      "erb-lint",
      "hadolint",
      "hlint",
      "protolint",
      "pyflakes",
      -- "pyre",
      -- "ast-grep",
      "dcm",
    },
  },
}
